<a href="https://colab.research.google.com/github/Shirivarshini/NHANES-Age-Classification/blob/main/notebooks/01_Data_Exploration_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NHANES Age Classification

## Stage 1: Dataset Exploration

**Objective:**
Understand the dataset before preprocessing and model building.

Dataset:
- Train_dataset.csv
- Test_dataset.csv
- Sample_submission.csv

In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

# Better plot style
plt.style.use("ggplot")

# Display all columns
pd.set_option("display.max_columns", None)

# Display numbers with 2 decimal places
pd.set_option("display.float_format", "{:.2f}".format)

In [3]:
train = pd.read_csv("Train_dataset.csv")
test = pd.read_csv("Test_dataset.csv")
sample = pd.read_csv("Sample_submission.csv")

In [4]:
print("Train Shape :", train.shape)
print("Test Shape  :", test.shape)
print("Sample Shape:", sample.shape)

Train Shape : (1966, 9)
Test Shape  : (312, 8)
Sample Shape: (312, 1)

In [5]:
train.head()

      SEQN  RIAGENDR  PAQ605  BMXBMI  LBXGLU  DIQ010  LBXGLT  LBXIN age_group
0 73564.00      2.00    2.00   35.70  110.00    2.00  150.00  14.91     Adult
1 73568.00      2.00    2.00   20.30   89.00    2.00   80.00   3.85     Adult
2 73576.00      1.00    2.00   23.20   89.00    2.00   68.00   6.14     Adult
3 73577.00      1.00    2.00   28.90  104.00     NaN   84.00  16.15     Adult
4 73580.00      2.00    1.00   35.90  103.00    2.00   81.00  10.92     Adult

In [6]:
train.tail()

,SEQN,RIAGENDR,PAQ605,BMXBMI,LBXGLU,DIQ010,LBXGLT,LBXIN,age_group
1961,83711.00,2.00,2.00,33.50,100.00,2.00,73.00,6.53,Adult
1962,83712.00,1.00,2.00,30.00,93.00,2.00,208.00,13.02,Adult
1963,83713.00,1.00,2.00,23.70,103.00,2.00,124.00,21.41,Adult
1964,83718.00,2.00,2.00,27.40,90.00,2.00,108.00,4.99,Adult
1965,83727.00,1.00,2.00,24.50,NaN,2.00,108.00,3.76,Adult

In [7]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1966 entries, 0 to 1965
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   SEQN       1954 non-null   float64
 1   RIAGENDR   1948 non-null   float64
 2   PAQ605     1953 non-null   float64
 3   BMXBMI     1948 non-null   float64
 4   LBXGLU     1953 non-null   float64
 5   DIQ010     1948 non-null   float64
 6   LBXGLT     1955 non-null   float64
 7   LBXIN      1957 non-null   float64
 8   age_group  1952 non-null   object
dtypes: float64(8), object(1)
memory usage: 138.4+ KB

In [8]:
train.describe()

          SEQN  RIAGENDR  PAQ605  BMXBMI  LBXGLU  DIQ010  LBXGLT   LBXIN
count  1954.00   1948.00 1953.00 1948.00 1953.00 1948.00 1955.00 1957.00
mean  78683.62      1.51    1.83   27.97   99.49    2.02  115.15   11.86
std    2924.12      0.50    0.40    7.33   16.77    0.19   46.27    9.76
min   73564.00      1.00    1.00   14.50   63.00    1.00   40.00    0.14
25%   76194.00      1.00    2.00   22.80   91.00    2.00   87.00    5.80
50%   78717.00      2.00    2.00   26.80   97.00    2.00  105.00    9.03
75%   81217.00      2.00    2.00   31.30  104.00    2.00  131.00   14.48
max   83727.00      2.00    7.00   70.10  405.00    3.00  604.00  102.29

In [9]:
train.describe(include="object")

       age_group
count       1952
unique         2
top        Adult
freq        1638

In [10]:
missing = train.isnull().sum()

missing = missing[missing > 0].sort_values(ascending=False)

missing

RIAGENDR     18
DIQ010       18
BMXBMI       18
age_group    14
LBXGLU       13
PAQ605       13
SEQN         12
LBXGLT       11
LBXIN         9
dtype: int64

In [11]:
missing_percent = (train.isnull().sum() / len(train) * 100)

missing_percent = missing_percent[missing_percent > 0].sort_values(ascending=False)

missing_percent

RIAGENDR    0.92
DIQ010      0.92
BMXBMI      0.92
age_group   0.71
LBXGLU      0.66
PAQ605      0.66
SEQN        0.61
LBXGLT      0.56
LBXIN       0.46
dtype: float64

In [12]:
print("Duplicate rows:", train.duplicated().sum())

Duplicate rows: 0

In [13]:
train["age_group"].value_counts()

train["age_group"].value_counts(normalize=True) * 100

age_group
Adult    83.91
Senior   16.09
Name: proportion, dtype: float64

In [14]:
train.columns.tolist()

['SEQN',
 'RIAGENDR',
 'PAQ605',
 'BMXBMI',
 'LBXGLU',
 'DIQ010',
 'LBXGLT',
 'LBXIN',
 'age_group']

In [15]:
train.dtypes

SEQN         float64
RIAGENDR     float64
PAQ605       float64
BMXBMI       float64
LBXGLU       float64
DIQ010       float64
LBXGLT       float64
LBXIN        float64
age_group     object
dtype: object